[build]
  base    = "frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_BASE = "https://school-finance-payment-and-dashboard.onrender.com"